### ISSUE TITLE
20231004 Feedback

### ISSUE THREAD

**Issue by MisooKim2** [jangyeseong757/C202309#2]
에러 있음. 아래 파일/에러메세지/솔루션을 확인하세요
- ERROR in challenge/week5/functionMulti
    - Error: conflicting types for 'multi' [line 12]
         - 이유: 선언된 함수의 원형이 선언되지 않았습니다.
         - 해결: 원형을 선언했다면 매개변수/반환데이터의 자료형이나 함수명을 확인하시고, 원형이 없다면 원형을 추가하세요. (함수명을 확인하세요.)

워닝 있음. 아래 파일/워닝메세지/솔루션을 확인하세요
- WARNING in challenge/week5/functionMulti
    - Warning: return type of 'main' is not 'int' [line 5] 
         - 이유: main의 반환값은 int 여야 합니다
         - 해결: void main()을 int main()으로 변경하고 마지막에 return 0;을 추가하세요.
    - Warning: implicit declaration of function 'multi' is invalid in C99 [line 7]
        - 이유: 함수원형이 선언되지 않았습니다.
        - 해결: main함수 위에 원형을 선언해주세요.
- WARNING in practice/week5/functionHap
    - Warning: return type of 'main' is not 'int' [line 5]
         - 이유: main의 반환값은 int 여야 합니다
         - 해결: void main()을 int main()으로 변경하고 마지막에 return 0;을 추가하세요.

**Comment by MisooKim2** [comment]
제가 수업시간에 void main() 함수에 대해 알려드렸었는데,
최근 컴파일러들이 해당 코드를 지양하는 추세라고 합니다.
하여 워닝 메세지에 추가되었으니 수정부탁드립니다.
관련하여 수업시간에 추가 공지하도록 하겠습니다.

**Comment by jangyeseong757** [comment]
수정 완료 하였습니다
