### ISSUE TITLE
20231031 중간 이전 전체 검토 결과

### ISSUE THREAD

**Issue by MisooKim2** [jangyeseong757/C202309#3]
### 없는 PDF 파일
- project/week8/todo_manager.pdf
	- 위 파일 이름이나 위치를 다시 확인하세요. 보고서 채점이 수행되지 않습니다.

### 에러 있음. 아래 파일/에러메세지/솔루션을 확인하세요
- ERROR in challenge/week3/choiceIf
    - Error: expected '}' [line 27]
        -  중괄호를 맞춰주세요.
- ERROR in challenge/week3/zeroTwoIf
    - Error: expected identifier or '(' [line 28]
        - 라인 끝에 ==== 를 지워주세요. 
- ERROR in challenge/week5/functionMulti
    - Error: conflicting types for 'multi' [line 12]
         - 함수 이름과 함수 내 변수 이름이 같아 multi가 무엇인지 명확히 할 수 없습니다. 변수 이름인 multi를 변경하거나, 함수 이름의 multi를 변경해주세요.
- ERROR in challenge/week6/studentGrade
    - Error: use of undeclared identifier 'STUDENT' [line 33]
        - 위 라인에 STUDENT라는 정의되지 않은 상수/변수를 사용하고 있습니다. STUDENTS로 오타를 수정해주세요. 
    - Error: expected ';' after expression [line 34]
        - 위 라인에 세미콜론을 추가해주세요. 

### 워닝 있음. 아래 파일/워닝메세지/솔루션을 확인하세요
- WARNING in challenge/week5/functionMulti
    - Warning: return type of 'main' is not 'int' [line 5]
        - main 함수의 반환형과 반환값을 추가해주세요.
    - Warning: implicit declaration of function 'multi' is invalid in C99 [line 7]
        - multi 함수의 원형이 선언되지 않았습니다. 코드 상단에 multi 함수 원형을 선언해주시거나, 기존 함수 원형의 이름을 변경해주세요. 
- WARNING in practice/week5/functionHap
    - Warning: return type of 'main' is not 'int' [line 5]
        - main 함수의 반환형과 반환값을 추가해주세요

### 기능/코드 대비 주석이 부족합니다. 주석을 추가하거나 쪼개세요.
- Insufficient comments in challenge/week3/do-while_even
- Insufficient comments in challenge/week3/while_even

**Comment by jangyeseong757** [comment]
수정 완료 하였습니다
